// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/personas": {
            "get": {
                "description": "Retorna todas las personas registradas",
                "produces": [
                    "application/json"
                ],
                "summary": "Listar personas",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.Persona"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Crea un nuevo registro de persona",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Agregar persona",
                "parameters": [
                    {
                        "description": "Datos de la persona",
                        "name": "persona",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.Persona"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/main.Persona"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/personas/{rut}": {
            "delete": {
                "description": "Elimina una persona por su RUT",
                "produces": [
                    "application/json"
                ],
                "summary": "Eliminar persona",
                "parameters": [
                    {
                        "type": "string",
                        "description": "RUT de la persona",
                        "name": "rut",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.Persona": {
            "type": "object",
            "properties": {
                "ciudad": {
                    "type": "string"
                },
                "fecha_nacimiento": {
                    "type": "string"
                },
                "gustos": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "nombre": {
                    "type": "string"
                },
                "rut": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Personas API",
	Description:      "API REST para gestión de personas — Segunda Evaluación Sumativa DevOps, UCN Coquimbo",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
